### PR TITLE
Rework engine and remove tokio

### PR DESCRIPTION
**Pull request by tyranron**
Related to #3  
Continues #4

## Overview

This PR introduces a new batch loading implementation using `futures` only and removes the necessity of using `tokio` crate.

## Motivation

Current batch loading implementation has the following drawbacks:
- _Thread spawning_. Each time `Loader` is created a new thread is spawned. As dataloader is a scope-based thing (lives in context of a concrete request) it means creating a new thread for every request, which has significant performance impact on a whole application.
- _Inevitability of `tokio` usage_. `Loader` creates new `tokio::runtime::current_thread` in a spawned thread. This means that library user has to use this runtime and cannot choose the desired runtime and guarantees for executing loading futures.
- _Eager loading_. `Loader::load()` sends task for loading to a separate thread via channel on its invocation. This means that loading may be performed even if returned `LoadFuture` has been never spawned. This conflicts with idiomatic Rust vision of futures being lazy: "Future does nothing unless polled".
- _Non-deterministic batching_. As tasks for loading are queued via channels to a separate thread which runs concurrently, the exact batch formation and execution depends on how concurrent threads are synchronized at a concrete moment in time, which leads to different batching results and guarantees on same inputs. For example, `example/simple.rs` performs differently on each execution:
    ```
    -- Using Cached Loader --
    load batch [3, 4]
    load batch [30, 35, 40, 45, 50]
    ```
    ```
     -- Using Cached Loader --
    load batch [3, 4]
    load batch [30, 35, 40]
    load batch [45, 50]
    ```

## Algorithm

The key point of dataloader implementation is an ability to defer loading until all the possible tasks for loading has been gathered. There is no general algorithm afaik, and each implementation does this trick on its own. For example, `graphql/dataloader` uses [Node.js-specific API or `setTimeout` hack](https://github.com/graphql/dataloader/blob/v1.4.0/src/index.js#L187-L221) for scheduling loading to the end of event loop, and `graph-gophers/dataloader` uses [`time.After` hack too](https://github.com/graph-gophers/dataloader/blob/v5.0.0/dataloader.go#L469-L477). ~~However, in Rust we are not required to poke with hacks as `std::futures` allows us to use `Waker` directly in `Future`, so we can easily reschedule future to the end of event loop.~~  
_Upd:_ In Rust we should use a hack with `Delay::new(Duration::from_nanos(1))` as using `Waker` directly does not defers future quite well.

This PR's implementation:
- ~~Uses `Waker` to reschedule enqueued loading task to the end of event loop, so that loading happens only when nothing more can be scheduled. Despite the fact that scheduled futures can be executed concurrently on `ThreadPool`, any new loading tasks are added to the end of event loop, so batching and loading have deterministic guarantees.~~  
_Upd:_ Uses `Delay::new(Duration::from_nanos(1))` to defer enqueued loading task asap. This, however, does not guarantees good deferring for batch loading, that's why the next step is required.
- ~~Does not enqueue anything if the `Future` returned by `Loader::load()` is never spawned. So meets the idiom "Future does nothing unless polled".~~  
_Upd:_ Eagerly enqueues loading task directly in `Loader::load()`. This partially violates the semantic "future does nothing unless polled". See [why](https://github.com/cksac/dataloader-rs/pull/5#issuecomment-502734094).
- Performs loading directly on the executor where  the `Future` returned by `Loader::load()` is spawned. So it's up to user to choose the desired runtime.

## Caveats

- Implementation internally uses `HashMap` (as a lot of index operation are performed), so the order of keys passed into `BatchFn::load()` is not historical (enqueuing order) due to `HashMap` having no ordering. This should not introduce any issue, however, as `BatchFn` implementation shouldn't depend on such things.
- ~~As loading is more lazy now, the `.cached()` version doesn't work always the way it has worked before. For example, `example/simple.rs` performs for this way now:~~

    ```
     -- Using Cached Loader --
    load batch [3, 4]
    load batch [30, 45, 40, 40, 35, 50]
    ```

    ~~As we see, no cache reads are involved as all keys of second stage are loaded at once.~~  
    ~~Currently, keys are not restricted with any trait bounds at all. In next PR I'll introduce dedupe adaptors for `K: PartialEq` keys, so we can omit passing duplicate keys to `BatchFn::load()`.~~
- A new type parameter `F: BatchFn` is imposed in `Loader` type. This, however, feels right as disallows mixing `Loader`s with different `BatchFn` on a type level (compile error).

## Checklist

- [x] Code is formatted with rustfmt.
- [x] Tests are updated and pass (removed `tokio` usage)
- [x] Example is updated (removed `tokio` usage) and new `tokio` example is created
- [x] README and crate description are updated

## Future work

- Try to lift more trait bounds for library's type params and reconsider library api  being more idiomatic with `std::futures` (non-error futures, etc).
- Introduce sort of `LocalLoader` to omit threads synchronization costs for use-cases where all happens in a single thread (relatively easy, just replace `Arc<Mutex<State>>` with `Rc<RefCell<State>>`).
- Add documentation, more examples and tests which check batching guarantees.

### CODE REVIEW

**Comment by cksac** [comment]
@tyranron I am look into the detail yet. For the lazy loading you mean the loader will not invoke loading when it reach max batch size? It will run multiple loading batch until first poll?

**Comment by tyranron** [comment]
@tyranron basically, batch loading will be invoked, when the future is polled second time (polled first time -> rescheduled with `.wake()` to the end of event loop -> polled second time -> invoke the loading). This allow to collect all the spawned futures. If their number > `max_batch_size` then multiple concurrent loadings will be invoked, otherwise (number <= `max_batch_size`) only one.

**Comment by cksac** [comment]
@tyranron thanks for your PR. In previous cached loader implementation which use `shared` to guarantee same key will have same result in each loader instance. I have bit concerns about losing this guarantee in this PR especially when the `batch_fn` doing some DB query under some use case, i.e. graphql query. Any thought?

**Comment by tyranron** [comment]
@cksac sorry for that.

In this PR I was concentrated mainly on `non_cached::Loader` implementation, so `cached::Loader` was "simplified" without a real necessity in that because I considered keeping `Future` in cache a little bit overcomplicated when we can just store values there. Now, after you've pointed out, I see the real reason why it was done so, which I didn't figure out before.

I'll revert these changes to support `shared` case you've described and will add a test case to track possible regression of this in future.

**Comment by tyranron** [comment]
@cksac the issue you had described helped me to spot major weaknesses in this implementation.

Firstly, this assumption turns out to be incorrect:
> However, in Rust we are not required to poke with hacks as std::futures allows us to use Waker directly in Future, so we can easily reschedule future to the end of event loop.

In practice, `Waker` doesn't reschedule future to the end of event loop. Very often it reschedules somewhere-in-the-middle, and quite often it reschedules it in-place continuing to polling this exact Future to completeness and totally ignoring other stuff that was scheduled earlier.

So, I had to use the trick other implementations do: `Delay::new(Duration::from_nanos(1))` 😕. This somehow defers next polling much better, and relatively does the thing, however...

Second, it turned out that full laziness breaks the deferring when it comes to futures with combinators (which is quite common for GraphQL resolving, or complex data queries, etc). For example, the code below (from `simple.rs` example):
```rust
let ld = Loader::new(Batcher).cached();
println!("\n -- Using Cached Loader --");
{
    let v1 = ld
        .load(3)
        .and_then(|v| ld.load_many(vec![v, v + 5, v + 10]));
    let v2 = ld
        .load(4)
        .and_then(|v| ld.load_many(vec![v, v + 5, v + 10]));
    let output = rt.run(future::try_join(v1, v2)).unwrap();
    let expected = (vec![300, 350, 400], vec![400, 450, 500]);
    assert_eq!(expected, output);
}
```
became non-deterministic again and sporadically was introducing different guarantees:
```
-- Using Cached Loader --
load batch [3, 4]
load batch [30, 35, 40, 45, 50]
```
```
 -- Using Cached Loader --
load batch [3, 4]
load batch [30, 35, 40]
load batch [45, 50]
```

The cause is that we wanted to enqueue key for loading _only if it was polled at least once_. However, _second poll_ (which does batch loading) _may happen earlier than first poll for other keys_, and that cannot be controlled at all. This issue is quite illustrative with `ThreadPool`:
```
thread1: ----[k1 1st poll]--[k1 2nd poll]-----------------------
thread2: ---------[lot of other stuff]-----------[k2 1st poll]--
```

This lead me to a necessity of enqueueing keys eagerly right in `Loader::load()` call. The downside is that this, in some sense, breaks the semantic "future does nothing unless polled", as may trigger batch loading for this key even it hasn't been polled, but saves this semantic for a case where nothing has been polled at all (to trigger batch loading at least one future from the set should be polled). The upside is the much more optimal deferring plan for major case, for example, the `simple.rs` described above performs _always_ with the following guarantees:
```
 -- Using Cached Loader --
load batch [3, 4]
load batch [40, 35, 50, 45, 30]
```
The decision is made assuming that partial dropping of `Loader::load()` futures is the minor case and multi-level futures combinators are the major case when using dataloader.

And, finally, your issue with shared cache should be totally fixed at the moment.

I'll update the PR description shortly.

**Comment by tyranron** [comment]
Done.

**Comment by cksac** [comment]
@tyranron thanks for the PR. we can see anything can be done about the `Delay` tick later.

**Pull request merged**
